version: '3.4'

services:
  server:
    image: 49623626/strapi_app
    volumes: 
      - .:/code
    ports:
      - "1337:1337"
  web:
    ports:
        - "3000:3000"
    image: 49623626/nextjs_app
    depends_on:
      - server